import type { RecipeSeed } from './build';

export const SEEDS_B: RecipeSeed[] = [
  {
    title: 'Skyr Berry Overnight Oats',
    description: 'Thick skyr oats set overnight with blueberries and chia.',
    servings: 1,
    prep: 5,
    cook: 0,
    cuisine: 'Other',
    course: 'breakfast',
    tags: ['quick', 'no cook'],
    subs: { Skyr: ['Greek yogurt 0%', 'Cottage cheese'], 'Milk 1.5%': ['Soy milk'] },
    ing: [
      ['Skyr', 200, 'g', 200, 'substitutable'],
      ['Rolled oats', 50, 'g', 50, 'core'],
      ['Blueberries', 80, 'g', 80, 'core'],
      ['Milk 1.5%', 80, 'ml', 80, 'substitutable'],
      ['Chia seeds', 1, 'tbsp', 12, 'optional'],
      ['Honey', 1, 'tsp', 7, 'optional'],
    ],
    steps: [
      'Stir the oats, chia, milk and half the skyr together in a jar.',
      'Fold in half the blueberries, crushing a few to bleed colour through.',
      'Refrigerate overnight, or at least four hours.',
      'Top with the remaining skyr, the rest of the berries and the honey.',
    ],
  },
  {
    title: 'Sheet-Pan Harissa Chicken and Squash',
    description: 'One tray, forty minutes, enough for two nights.',
    servings: 2,
    prep: 10,
    cook: 30,
    cuisine: 'Other',
    course: 'dinner',
    tags: ['high protein', 'batch'],
    subs: { Harissa: ['Gochujang'] },
    ing: [
      ['Chicken breast', 300, 'g', 300, 'core'],
      ['Butternut squash', 400, 'g', 400, 'core', 'in 2cm cubes'],
      ['Red onion', 150, 'g', 150, 'core', 'in thick wedges'],
      ['Chickpeas', 150, 'g', 150, 'optional'],
      ['Harissa', 2, 'tbsp', 32, 'substitutable'],
      ['Greek yogurt 0%', 80, 'g', 80, 'optional'],
      ['Parsley', 15, 'g', 15, 'optional'],
      ['Olive oil', 1, 'tbsp', 13.5, 'basic'],
      ['Ground cumin', 1, 'tsp', 2, 'basic'],
      ['Salt', null, 'pinch', 2, 'basic'],
    ],
    steps: [
      'Heat the oven to 220C. Toss the squash and onion with half the oil, the cumin and salt.',
      'Roast for 15 minutes while you rub the chicken with the harissa and remaining oil.',
      'Add the chicken and chickpeas to the tray and roast a further 15 minutes.',
      'Rest the chicken for 5 minutes, then slice thickly.',
      'Serve with the yogurt spooned over and plenty of parsley.',
    ],
  },
  {
    title: 'Big Kale Caesar with Halloumi',
    description: 'Massaged kale, a yogurt caesar and hot squeaky halloumi.',
    servings: 1,
    prep: 10,
    cook: 10,
    cuisine: 'Mediterranean',
    course: 'lunch',
    tags: ['high volume'],
    subs: { Halloumi: ['Firm tofu', 'Chicken breast'] },
    ing: [
      ['Kale', 120, 'g', 120, 'core', 'stems removed'],
      ['Romaine lettuce', 100, 'g', 100, 'core'],
      ['Halloumi', 80, 'g', 80, 'substitutable'],
      ['Greek yogurt 0%', 70, 'g', 70, 'core'],
      ['Cherry tomatoes', 100, 'g', 100, 'optional'],
      ['Parmesan', 10, 'g', 10, 'optional'],
      ['Olive oil', 7, 'g', 7, 'basic'],
      ['Lemon juice', 1, 'tbsp', 15, 'basic'],
      ['Dijon mustard', 1, 'tsp', 5, 'basic'],
      ['Garlic', 1, 'clove', 4, 'basic'],
    ],
    steps: [
      'Massage the torn kale with a little olive oil and salt for a minute until it darkens and softens.',
      'Whisk yogurt, lemon, dijon, crushed garlic and grated parmesan into a dressing.',
      'Fry the sliced halloumi dry in a hot non-stick pan until browned on both sides.',
      'Toss the kale, romaine and tomatoes through the dressing.',
      'Top with the hot halloumi and eat immediately.',
    ],
  },
  {
    title: 'Black Bean and Sweet Potato Tacos',
    description: 'Cumin-roasted sweet potato, black beans and pickled red cabbage.',
    servings: 2,
    prep: 10,
    cook: 20,
    cuisine: 'Mexican',
    course: 'dinner',
    tags: ['vegetarian'],
    subs: { Avocado: ['Greek yogurt 0%'] },
    ing: [
      ['Sweet potato', 400, 'g', 400, 'core', 'in 2cm cubes'],
      ['Black beans', 240, 'g', 240, 'core'],
      ['Corn tortilla', 6, 'piece', 156, 'core'],
      ['Red cabbage', 120, 'g', 120, 'optional', 'finely shredded'],
      ['Avocado', 70, 'g', 70, 'substitutable'],
      ['Coriander', 15, 'g', 15, 'optional'],
      ['Lime', null, 'piece', 25, 'basic'],
      ['Ground cumin', 1.5, 'tsp', 3, 'basic'],
      ['Smoked paprika', 1, 'tsp', 2, 'basic'],
      ['Rapeseed oil', 9, 'g', 9, 'basic'],
    ],
    steps: [
      'Toss the sweet potato with oil, cumin and paprika and roast at 220C for 20 minutes.',
      'Meanwhile squeeze lime over the shredded cabbage with a pinch of salt and leave to soften.',
      'Warm the beans through with a splash of their liquid and crush lightly.',
      'Char the tortillas directly over a flame or in a dry pan.',
      'Build with beans, sweet potato, cabbage, avocado and coriander.',
    ],
  },
  {
    title: 'Cottage Cheese Protein Pancakes',
    description: 'Blender pancakes that hold together and actually fill you up.',
    servings: 1,
    prep: 5,
    cook: 10,
    cuisine: 'Other',
    course: 'breakfast',
    tags: ['high protein', 'quick'],
    subs: { 'Cottage cheese': ['Skyr', 'Greek yogurt 0%'] },
    ing: [
      ['Cottage cheese', 150, 'g', 150, 'substitutable'],
      ['Egg', 2, 'piece', 116, 'core'],
      ['Rolled oats', 45, 'g', 45, 'core'],
      ['Blueberries', 60, 'g', 60, 'optional'],
      ['Maple syrup', 1, 'tbsp', 20, 'optional'],
      ['Vanilla extract', 1, 'tsp', 4, 'basic'],
      ['Rapeseed oil', 4.5, 'g', 4.5, 'basic'],
    ],
    steps: [
      'Blend the cottage cheese, eggs, oats and vanilla until completely smooth.',
      'Let the batter stand for 5 minutes so the oats hydrate and it thickens.',
      'Cook in a lightly oiled non-stick pan over medium-low heat, three or four at a time.',
      'Flip when the surface bubbles and the edges set.',
      'Stack with blueberries and a thread of maple syrup.',
    ],
  },
  {
    title: 'Tuna and White Bean Salad',
    description: 'Store-cupboard lunch with an unreasonable amount of protein.',
    servings: 1,
    prep: 10,
    cook: 0,
    cuisine: 'Italian',
    course: 'lunch',
    tags: ['high protein', 'quick', 'no cook'],
    subs: { 'Cannellini beans': ['Chickpeas'] },
    ing: [
      ['Tuna in water', 1, 'can', 145, 'core', 'drained'],
      ['Cannellini beans', 200, 'g', 200, 'substitutable'],
      ['Cherry tomatoes', 120, 'g', 120, 'core', 'halved'],
      ['Red onion', 40, 'g', 40, 'optional', 'sliced paper thin'],
      ['Rocket', 40, 'g', 40, 'optional'],
      ['Parsley', 10, 'g', 10, 'optional'],
      ['Olive oil', 10, 'g', 10, 'basic'],
      ['Lemon juice', 1, 'tbsp', 15, 'basic'],
      ['Black pepper', null, 'pinch', 0.5, 'basic'],
    ],
    steps: [
      'Soak the sliced red onion in the lemon juice for 5 minutes to take the edge off.',
      'Fold the beans, tuna and tomatoes together without mashing the beans.',
      'Dress with the lemony onion, olive oil and plenty of black pepper.',
      'Fold the rocket and parsley through at the last moment.',
    ],
  },
];
