import type { RecipeSeed } from './build';

export const SEEDS_A: RecipeSeed[] = [
  {
    title: 'Crispy Tofu Caesar Wrap',
    description: 'Cornflour-crisped tofu, cold romaine and a yogurt caesar in a protein wrap.',
    servings: 1,
    prep: 10,
    cook: 10,
    cuisine: 'Other',
    course: 'lunch',
    tags: ['quick'],
    subs: { Parmesan: ['Nutritional yeast'], 'Protein tortilla': ['Wholewheat tortilla'] },
    ing: [
      ['Firm tofu', 150, 'g', 150, 'core', 'pressed and torn'],
      ['Protein tortilla', 1, 'piece', 45, 'core'],
      ['Romaine lettuce', 80, 'g', 80, 'core', 'shredded'],
      ['Greek yogurt 0%', 60, 'g', 60, 'core'],
      ['Parmesan', 12, 'g', 12, 'substitutable', 'finely grated'],
      ['Cornflour', 1, 'tbsp', 8, 'basic'],
      ['Dijon mustard', 1, 'tsp', 5, 'basic'],
      ['Lemon juice', 1, 'tbsp', 15, 'basic'],
      ['Olive oil', 1, 'tsp', 4.5, 'basic'],
      ['Garlic', 1, 'clove', 4, 'basic'],
      ['Black pepper', null, 'pinch', 0.5, 'basic'],
    ],
    steps: [
      'Tear the pressed tofu into rough bite-size pieces and toss with cornflour and a pinch of salt.',
      'Fry in the olive oil over medium-high heat, undisturbed, until deeply golden on two sides.',
      'Whisk the yogurt, grated parmesan, dijon, lemon juice, crushed garlic and pepper into a dressing.',
      'Toss the shredded romaine through the dressing, then fold in the tofu.',
      'Pile into the warmed tortilla and roll tightly.',
    ],
  },
  {
    title: 'Charred Broccoli and Chickpea Bowl',
    description: 'Hard-roasted broccoli and crisp chickpeas over quinoa with lemon tahini.',
    servings: 1,
    prep: 10,
    cook: 20,
    cuisine: 'Mediterranean',
    course: 'dinner',
    tags: ['high volume', 'vegetarian'],
    subs: { 'Quinoa, cooked': ['Brown rice, cooked', 'Couscous, cooked'], Tahini: ['Greek yogurt 0%'] },
    ing: [
      ['Broccoli', 200, 'g', 200, 'core', 'cut into small florets'],
      ['Chickpeas', 150, 'g', 150, 'core', 'drained and dried'],
      ['Quinoa, cooked', 120, 'g', 120, 'substitutable'],
      ['Tahini', 15, 'g', 15, 'substitutable'],
      ['Rocket', 30, 'g', 30, 'optional'],
      ['Pumpkin seeds', 12, 'g', 12, 'optional'],
      ['Lemon juice', 1, 'tbsp', 15, 'basic'],
      ['Olive oil', 7, 'g', 7, 'basic'],
      ['Garlic', 1, 'clove', 4, 'basic'],
      ['Chilli flakes', null, 'pinch', 1, 'basic'],
      ['Salt', null, 'pinch', 1, 'basic'],
    ],
    steps: [
      'Heat the oven as high as it goes. Toss broccoli and chickpeas with the olive oil, chilli and salt.',
      'Roast on a preheated tray for 18 to 20 minutes, until the florets are blackened at the edges.',
      'Loosen the tahini with lemon juice, crushed garlic and cold water until pourable.',
      'Spoon the quinoa into a wide bowl, top with the roasted tray, rocket and pumpkin seeds.',
      'Spoon over the tahini and finish with more lemon.',
    ],
  },
  {
    title: 'Gochujang Salmon Rice Bowl',
    description: 'Glazed salmon, wilted pak choi and kimchi over brown rice.',
    servings: 1,
    prep: 10,
    cook: 15,
    cuisine: 'Korean',
    course: 'dinner',
    tags: ['high protein'],
    subs: { 'Brown rice, cooked': ['White rice, cooked'] },
    ing: [
      ['Salmon fillet', 1, 'piece', 130, 'core'],
      ['Brown rice, cooked', 150, 'g', 150, 'substitutable'],
      ['Pak choi', 120, 'g', 120, 'core', 'halved lengthways'],
      ['Gochujang', 1, 'tbsp', 18, 'core'],
      ['Kimchi', 60, 'g', 60, 'optional'],
      ['Spring onion', 1, 'piece', 15, 'optional'],
      ['Sesame seeds', 5, 'g', 5, 'optional'],
      ['Soy sauce', 8, 'g', 8, 'basic'],
      ['Sesame oil', 1, 'tsp', 4.5, 'basic'],
      ['Ginger', 1, 'tbsp', 6, 'basic', 'grated'],
    ],
    steps: [
      'Mix the gochujang, soy sauce, sesame oil and grated ginger into a glaze.',
      'Sear the salmon skin-side down until the skin releases, then flip and brush generously with the glaze.',
      'Finish under a hot grill for 2 minutes so the glaze catches.',
      'Wilt the pak choi in the same pan with a splash of water.',
      'Build over the rice with kimchi, sliced spring onion and sesame seeds.',
    ],
  },
  {
    title: 'Green Shakshuka',
    description: 'Eggs baked into a pan of spinach, courgette and feta.',
    servings: 2,
    prep: 10,
    cook: 15,
    cuisine: 'Mediterranean',
    course: 'breakfast',
    tags: ['high volume', 'vegetarian'],
    subs: { Feta: ['Ricotta', 'Cottage cheese'] },
    ing: [
      ['Egg', 4, 'piece', 232, 'core'],
      ['Spinach', 300, 'g', 300, 'core'],
      ['Courgette', 1, 'piece', 200, 'core', 'coarsely grated'],
      ['Onion', 1, 'piece', 80, 'core', 'finely sliced'],
      ['Feta', 60, 'g', 60, 'substitutable', 'crumbled'],
      ['Coriander', 15, 'g', 15, 'optional'],
      ['Olive oil', 1, 'tbsp', 13.5, 'basic'],
      ['Garlic', 2, 'clove', 8, 'basic'],
      ['Ground cumin', 1, 'tsp', 2, 'basic'],
      ['Chilli flakes', null, 'pinch', 1, 'basic'],
    ],
    steps: [
      'Soften the onion in olive oil, then add garlic, cumin and chilli for a minute.',
      'Add the grated courgette and cook hard until the water has gone.',
      'Wilt in the spinach a handful at a time and season well.',
      'Make four wells, crack in the eggs, cover and cook until the whites just set.',
      'Scatter with feta and coriander.',
    ],
  },
  {
    title: 'Cold Sesame Cucumber Noodles',
    description: 'Smashed cucumber and udon in a sharp peanut-sesame sauce.',
    servings: 1,
    prep: 15,
    cook: 0,
    cuisine: 'Japanese',
    course: 'lunch',
    tags: ['quick', 'no cook'],
    subs: { 'Udon noodles, cooked': ['Wholewheat pasta, cooked'] },
    ing: [
      ['Udon noodles, cooked', 180, 'g', 180, 'core'],
      ['Cucumber', 150, 'g', 150, 'core', 'smashed and torn'],
      ['Peanut butter', 1.5, 'tbsp', 24, 'core'],
      ['Spring onion', 1, 'piece', 15, 'optional'],
      ['Sesame seeds', 5, 'g', 5, 'optional'],
      ['Soy sauce', 1, 'tbsp', 16, 'basic'],
      ['Rice vinegar', 1, 'tbsp', 15, 'basic'],
      ['Sesame oil', 1, 'tsp', 4.5, 'basic'],
      ['Garlic', 1, 'clove', 4, 'basic'],
      ['Chilli flakes', null, 'pinch', 1, 'basic'],
    ],
    steps: [
      'Smash the cucumber with the flat of a knife, tear into pieces and salt lightly for 10 minutes.',
      'Whisk peanut butter, soy, rice vinegar, sesame oil, crushed garlic and chilli with a little hot water.',
      'Rinse the cooked noodles under cold water until properly cold.',
      'Drain the cucumber, then toss everything together.',
      'Top with spring onion and sesame seeds.',
    ],
  },
  {
    title: 'Red Lentil Coconut Soup',
    description: 'A thick, spiced lentil soup that gets better on the second day.',
    servings: 3,
    prep: 10,
    cook: 25,
    cuisine: 'Indian',
    course: 'dinner',
    tags: ['high volume', 'batch', 'vegetarian'],
    subs: { 'Light coconut milk': ['Soy milk'] },
    ing: [
      ['Red lentils', 450, 'g', 450, 'core', 'cooked weight'],
      ['Vegetable stock', 600, 'ml', 600, 'core'],
      ['Light coconut milk', 200, 'ml', 200, 'substitutable'],
      ['Carrot', 2, 'piece', 150, 'core'],
      ['Onion', 1, 'piece', 110, 'core'],
      ['Coriander', 20, 'g', 20, 'optional'],
      ['Tomato paste', 2, 'tbsp', 32, 'basic'],
      ['Curry powder', 3, 'tsp', 6, 'basic'],
      ['Ginger', 2, 'tbsp', 12, 'basic'],
      ['Garlic', 2, 'clove', 8, 'basic'],
      ['Rapeseed oil', 1, 'tbsp', 13.5, 'basic'],
    ],
    steps: [
      'Sweat the onion and carrot in the oil for 8 minutes without colouring.',
      'Add garlic, ginger, curry powder and tomato paste and fry until fragrant and darkened.',
      'Add the lentils and stock, bring to a simmer and cook for 15 minutes.',
      'Stir through the coconut milk and blend about half the pot, leaving texture.',
      'Season aggressively and finish with coriander.',
    ],
  },
];
