import type { RecipeSeed } from './build';

export const SEEDS_C: RecipeSeed[] = [
  {
    title: 'Spiced Turkey Lettuce Cups',
    description: 'Gochujang turkey spooned into cold lettuce with pickled carrot.',
    servings: 2,
    prep: 10,
    cook: 10,
    cuisine: 'Korean',
    course: 'dinner',
    tags: ['high protein', 'high volume'],
    subs: { 'Turkey mince': ['Lean beef mince', 'Firm tofu'], Gochujang: ['Harissa'] },
    ing: [
      ['Turkey mince', 300, 'g', 300, 'core'],
      ['Romaine lettuce', 200, 'g', 200, 'core', 'leaves separated'],
      ['Gochujang', 25, 'g', 25, 'substitutable'],
      ['Carrot', 100, 'g', 100, 'optional', 'julienned'],
      ['Cucumber', 100, 'g', 100, 'optional'],
      ['Spring onion', 20, 'g', 20, 'optional'],
      ['Soy sauce', 1, 'tbsp', 16, 'basic'],
      ['Sesame oil', 1, 'tsp', 4.5, 'basic'],
      ['Garlic', 2, 'clove', 8, 'basic'],
      ['Ginger', 1, 'tbsp', 6, 'basic'],
    ],
    steps: [
      'Brown the turkey hard in a dry pan, breaking it up, until some of it crisps.',
      'Add garlic and ginger, then the gochujang, soy and sesame oil.',
      'Cook another two minutes until glossy and clinging.',
      'Spoon into cold lettuce leaves with carrot, cucumber and spring onion.',
    ],
  },
  {
    title: 'Courgette and Ricotta Pasta',
    description: 'Courgette cooked down to a sauce, loosened with ricotta and lemon.',
    servings: 2,
    prep: 10,
    cook: 15,
    cuisine: 'Italian',
    course: 'dinner',
    tags: ['vegetarian'],
    subs: { Ricotta: ['Cottage cheese'], 'Wholewheat pasta, cooked': ['Pasta, cooked'] },
    ing: [
      ['Wholewheat pasta, cooked', 400, 'g', 400, 'substitutable'],
      ['Courgette', 350, 'g', 350, 'core', 'sliced into thin coins'],
      ['Ricotta', 150, 'g', 150, 'substitutable'],
      ['Parmesan', 25, 'g', 25, 'optional'],
      ['Basil', 15, 'g', 15, 'optional'],
      ['Lemon', 20, 'g', 20, 'optional', 'zest only'],
      ['Olive oil', 1, 'tbsp', 13.5, 'basic'],
      ['Garlic', 2, 'clove', 8, 'basic'],
      ['Chilli flakes', null, 'pinch', 1, 'basic'],
    ],
    steps: [
      'Cook the courgette in olive oil over medium heat for 12 minutes until collapsed and sweet.',
      'Add the garlic and chilli for the last minute.',
      'Take off the heat and stir in the ricotta and lemon zest with a ladle of pasta water.',
      'Toss the pasta through until the sauce coats every piece.',
      'Finish with parmesan and torn basil.',
    ],
  },
  {
    title: 'Dark Chocolate Chia Pudding',
    description: 'A dessert that is mostly seeds and cocoa, and tastes like it should not be.',
    servings: 2,
    prep: 10,
    cook: 0,
    cuisine: 'Other',
    course: 'dessert',
    tags: ['no cook'],
    subs: { 'Soy milk': ['Milk 1.5%'] },
    ing: [
      ['Soy milk', 400, 'ml', 400, 'substitutable'],
      ['Chia seeds', 48, 'g', 48, 'core'],
      ['Cocoa powder', 3, 'tbsp', 15, 'core'],
      ['Maple syrup', 1.5, 'tbsp', 30, 'optional'],
      ['Dark chocolate 85%', 20, 'g', 20, 'optional', 'shaved'],
      ['Raspberries', 80, 'g', 80, 'optional'],
      ['Vanilla extract', 1, 'tsp', 4, 'basic'],
    ],
    steps: [
      'Whisk the cocoa into a little of the milk first to avoid lumps.',
      'Add the remaining milk, chia, maple syrup and vanilla and whisk well.',
      'Whisk again after 10 minutes to stop the seeds settling.',
      'Chill for at least 3 hours until set.',
      'Top with raspberries and shaved dark chocolate.',
    ],
  },
  {
    title: 'Prawn Kimchi Fried Rice',
    description: 'Day-old rice, plenty of kimchi, and a fried egg on top.',
    servings: 1,
    prep: 5,
    cook: 15,
    cuisine: 'Korean',
    course: 'dinner',
    tags: ['high protein', 'quick'],
    subs: { 'White rice, cooked': ['Brown rice, cooked'], Prawns: ['Firm tofu', 'Chicken breast'] },
    ing: [
      ['Prawns', 150, 'g', 150, 'substitutable'],
      ['White rice, cooked', 180, 'g', 180, 'substitutable', 'cold, day old'],
      ['Kimchi', 100, 'g', 100, 'core', 'roughly chopped'],
      ['Egg', 1, 'piece', 58, 'optional'],
      ['Peas', 60, 'g', 60, 'optional'],
      ['Spring onion', 1, 'piece', 15, 'optional'],
      ['Soy sauce', 1, 'tbsp', 16, 'basic'],
      ['Sesame oil', 1, 'tsp', 4.5, 'basic'],
      ['Garlic', 1, 'clove', 4, 'basic'],
    ],
    steps: [
      'Get the pan properly hot. Fry the kimchi in the sesame oil until the edges caramelise.',
      'Add the garlic, then the prawns, and cook until just opaque.',
      'Add the cold rice and peas and press it flat, leaving it to catch before stirring.',
      'Season with soy sauce and fold through the spring onion.',
      'Top with a fried egg with a crisp lacy edge.',
    ],
  },
  {
    title: 'Mediterranean Quinoa Jar',
    description: 'Built in the jar the night before, dressed from the bottom up.',
    servings: 1,
    prep: 15,
    cook: 0,
    cuisine: 'Mediterranean',
    course: 'lunch',
    tags: ['no cook', 'meal prep'],
    subs: { Feta: ['Cottage cheese'], 'Quinoa, cooked': ['Couscous, cooked'] },
    ing: [
      ['Quinoa, cooked', 150, 'g', 150, 'core'],
      ['Chickpeas', 120, 'g', 120, 'core'],
      ['Cucumber', 120, 'g', 120, 'core', 'diced'],
      ['Cherry tomatoes', 120, 'g', 120, 'core', 'halved'],
      ['Feta', 40, 'g', 40, 'substitutable'],
      ['Red onion', 30, 'g', 30, 'optional'],
      ['Mint', 8, 'g', 8, 'optional'],
      ['Olive oil', 10, 'g', 10, 'basic'],
      ['Lemon juice', 1, 'tbsp', 15, 'basic'],
    ],
    steps: [
      'Whisk the olive oil and lemon juice with salt and pepper in the bottom of the jar.',
      'Layer the onion and chickpeas first so they sit in the dressing.',
      'Add cucumber and tomatoes, then the quinoa, keeping the layers distinct.',
      'Finish with feta and mint and seal.',
      'Shake hard just before eating.',
    ],
  },
  {
    title: 'Miso Mushroom Udon',
    description: 'Two kinds of mushroom, a savoury miso broth and thick udon.',
    servings: 1,
    prep: 10,
    cook: 10,
    cuisine: 'Japanese',
    course: 'dinner',
    tags: ['high volume', 'vegetarian'],
    subs: { 'Firm tofu': ['Egg'] },
    ing: [
      ['Udon noodles, cooked', 200, 'g', 200, 'core'],
      ['Shiitake mushrooms', 120, 'g', 120, 'core', 'sliced'],
      ['Mushrooms', 100, 'g', 100, 'core'],
      ['Pak choi', 150, 'g', 150, 'core'],
      ['Miso paste', 2, 'tbsp', 34, 'core'],
      ['Firm tofu', 100, 'g', 100, 'substitutable'],
      ['Spring onion', 1, 'piece', 15, 'optional'],
      ['Soy sauce', 1, 'tbsp', 16, 'basic'],
      ['Sesame oil', 1, 'tsp', 4.5, 'basic'],
      ['Garlic', 1, 'clove', 4, 'basic'],
    ],
    steps: [
      'Fry both mushrooms in a dry pan until they squeak, then add the sesame oil and garlic.',
      'Whisk the miso with 300ml hot water and the soy sauce. Do not boil it once added.',
      'Add the pak choi and tofu to the pan and pour over the miso broth.',
      'Warm through for two minutes, then add the udon.',
      'Serve in a deep bowl with spring onion.',
    ],
  },
];
